services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres_db
    restart: always
    ports:
      - "5432:5432" # Відкриваємо порт 5432 на твоєму комп'ютері
    environment:
      POSTGRES_USER: user_admin
      POSTGRES_PASSWORD: super_secret_password
      POSTGRES_DB: litebank_main_db
      POSTGRES_MULTIPLE_DATABASES: "auth_service_db:auth_user:auth_pass123,accounts_db:accounts_user:accounts_pass123,transactions_db:transactions_user:transactions_pass123,ledger_db:ledger_user:ledger_pass123"
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./init-multiple-databases.sh:/docker-entrypoint-initdb.d/init-multiple-databases.sh