services:
  kafka:
    build:
      context: ./kafka
      dockerfile: Dockerfile
    container_name: kafka
    ports:
      - "9094:9094"
    environment:
      # Налаштування режиму KRaft
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:9093'

      # Слухачі: внутрішній (9092) для Docker, зовнішній (9094) для ПК
      KAFKA_LISTENERS: 'INTERNAL://:9092,EXTERNAL://:9094,CONTROLLER://:9093'
      KAFKA_ADVERTISED_LISTENERS: 'INTERNAL://kafka:9092,EXTERNAL://localhost:9094'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'INTERNAL'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'

      # Фіксований Cluster ID, щоб не було конфліктів при перезапусках
      KAFKA_CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qg'
    volumes:
      - kafka_data:/var/lib/kafka/data

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8080:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local-kafka
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
    depends_on:
      - kafka


  postgres:
    image: postgres:16-alpine
    container_name: postgres_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user_admin
      POSTGRES_PASSWORD: super_secret_password
      POSTGRES_DB: litebank_main_db

      # Формат: назва_бд:юзер:пароль, назва_бд2:юзер2:пароль2
      POSTGRES_MULTIPLE_DATABASES: "
      auth_service_db:auth_user:auth_pass123,
      accounts_db:accounts_user:accounts_pass123,
      transactions_db:transactions_user:transactions_pass123,
      ledger_db:ledger_user:ledger_pass123
      "
    volumes:
      - ./PostgreSql/data:/var/lib/postgresql/data
      - ./PostgreSql/init-multiple-databases.sh:/docker-entrypoint-initdb.d/init-multiple-databases.sh

  auth-service:
    build: ./AuthService
    container_name: auth_service
    ports:
      - "5001:5000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://auth_user:auth_pass123@postgres_db:5432/auth_service_db
    volumes:
      - ./AuthService:/app
    command: uvicorn main:app --host 0.0.0.0 --port 5000 --reload
    depends_on:
      - postgres

volumes:
  kafka_data:
    driver: local