"""-

Revision ID: 65acefdbc4b0
Revises: 74f227db6ce3
Create Date: 2026-07-02 10:52:52.058591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65acefdbc4b0'
down_revision: Union[str, Sequence[str], None] = '74f227db6ce3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email3', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_email3'), 'users', ['email3'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email3'), table_name='users')
    op.drop_column('users', 'email3')
    # ### end Alembic commands ###
