"""-

Revision ID: 850f5f561dce
Revises: 3e7a31afbe36
Create Date: 2026-07-02 11:07:19.725322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '850f5f561dce'
down_revision: Union[str, Sequence[str], None] = '3e7a31afbe36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_email'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_email2'), table_name='transactions')
    op.drop_column('transactions', 'email2')
    op.drop_column('transactions', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('transactions', sa.Column('email2', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_transactions_email2'), 'transactions', ['email2'], unique=True)
    op.create_index(op.f('ix_transactions_email'), 'transactions', ['email'], unique=True)
    # ### end Alembic commands ###
