"""-

Revision ID: ffce51359106
Revises: ef06e079b9ef
Create Date: 2026-07-02 10:59:42.617749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffce51359106'
down_revision: Union[str, Sequence[str], None] = 'ef06e079b9ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('PhoneAutrh', sa.String(), nullable=True))
    op.drop_index(op.f('ix_users_email2'), table_name='users')
    op.drop_index(op.f('ix_users_email3'), table_name='users')
    op.drop_column('users', 'email3')
    op.drop_column('users', 'email2')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email2', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('email3', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_users_email3'), 'users', ['email3'], unique=True)
    op.create_index(op.f('ix_users_email2'), 'users', ['email2'], unique=True)
    op.drop_column('users', 'PhoneAutrh')
    # ### end Alembic commands ###
