"""-

Revision ID: 5fc7650cc168
Revises: 31f6e57fec43
Create Date: 2026-07-02 10:46:11.047672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fc7650cc168'
down_revision: Union[str, Sequence[str], None] = '31f6e57fec43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email2', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_email2'), 'users', ['email2'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email2'), table_name='users')
    op.drop_column('users', 'email2')
    # ### end Alembic commands ###
