"""-

Revision ID: 6299851750ec
Revises: 5fc7650cc168
Create Date: 2026-07-02 11:06:38.324142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6299851750ec'
down_revision: Union[str, Sequence[str], None] = '5fc7650cc168'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('users', sa.Column('phone3', sa.String(), nullable=True))
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_email2'), table_name='users')
    op.drop_column('users', 'email2')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email2', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_users_email2'), 'users', ['email2'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_column('users', 'phone3')
    op.drop_column('users', 'phone')
    # ### end Alembic commands ###
