"""-

Revision ID: b0f69bbc2df0
Revises: 190e562556ce
Create Date: 2026-07-04 15:23:31.450868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0f69bbc2df0'
down_revision: Union[str, Sequence[str], None] = '190e562556ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('cards_account_id_key'), 'cards', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('cards_account_id_key'), 'cards', ['account_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
