"""-

Revision ID: b71786a0659e
Revises: 40b21da8ee1a
Create Date: 2026-07-04 12:50:45.202982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b71786a0659e'
down_revision: Union[str, Sequence[str], None] = '40b21da8ee1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_accounts_username'), table_name='accounts')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_accounts_username'), 'accounts', ['username'], unique=True)
    # ### end Alembic commands ###
