"""-

Revision ID: fc826b913a7f
Revises: fc222997c080
Create Date: 2026-07-04 13:44:28.169606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc826b913a7f'
down_revision: Union[str, Sequence[str], None] = 'fc222997c080'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('card_number', sa.String(length=16), nullable=False),
    sa.Column('expiration_date', sa.String(length=5), nullable=False),
    sa.Column('cvv', sa.String(length=3), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cards_card_number'), 'cards', ['card_number'], unique=True)
    op.create_index(op.f('ix_cards_id'), 'cards', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cards_id'), table_name='cards')
    op.drop_index(op.f('ix_cards_card_number'), table_name='cards')
    op.drop_table('cards')
    # ### end Alembic commands ###
